/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopseminar2;

import oopseminar2.controller.Controller;
import oopseminar2.data.Teacher;
import oopseminar2.service.StudyGroupService;

public class App {
    public static void main(String[] args) {
        Controller controller = new Controller();
        //Создаём пару юзеров студентов
        controller.createUser("Ivan", "Tretyakov" , "Ivanovic");
        controller.createUser("Dmitry", "Kuznecov" , "Vladimirovich");
        Teacher teacher = new Teacher("Olga", "Petrova", "Ivanovna", 1L);
        StudyGroupService studyGroupService = new StudyGroupService();
        controller.createStudyGroup(teacher, studyGroupService.get);
    } 
}
